### ISSUE TITLE
Products part

### ISSUE THREAD

**Issue by Endrju00** [Endrju00/ShopManager#1]
### It includes entities such as
* Wholesalers (Hurtownie)
* Delivered items (Dostarczone towary)
* Products (Produkty)
* Producers (Producenci)
* Categories (Kategorie)

### Tasks
- [x] Create models connected with products
- [x] Create views connected with products
- [x] Configure urls connected with products
