### ISSUE TITLE
Change database 

### ISSUE THREAD

**Issue by Endrju00** [Endrju00/ShopManager#17]
### Tasks
- [x] Configurate the database
- [x] Configurate the project
- [x] Store one function and one procedure (requirement from the lecturer)
