### ISSUE TITLE
Orders part

### ISSUE THREAD

**Issue by Endrju00** [Endrju00/ShopManager#2]
### It includes entities such as
* Orders (Zamówienia)
* Items in the orders (Pozycje w zamówieniach)
* Payments (Płatności)
* Addresses (Adresy)

### Tasks
- [x] Create models connected with orders
- [x] Create views connected with  orders
- [x] Configure urls connected with  orders
