### ISSUE TITLE
Employees part

### ISSUE THREAD

**Issue by Endrju00** [Endrju00/ShopManager#3]
### It includes entities such as
* Employees (Pracownicy)
* Positions (Stanowiska)

### Tasks
- [x] Create models connected with employees
- [x] Create views connected with employees
- [x] Configure urls connected with employees
