### ISSUE TITLE
Clients part

### ISSUE THREAD

**Issue by Endrju00** [Endrju00/ShopManager#4]
### It includes entities such as
* Clients (Klienci)

### Tasks
- [x] Create models connected with clients
- [x] Create views connected with clients
- [x] Configure urls connected with clients
